---
- name: Hello World
  hosts: localhost
  connection: local
  tasks:

    - name: Disk usage from command module
      command: df -h
      register: space
    - debug:
        var: space

    - name: Creating a new directory
      file:
        path: "foo/"
        state: directory

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    - name: Create file
      ansible.builtin.file:
        path: foo/foo.txt
        state: touch

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    - name: Copy file
      ansible.builtin.copy:
        src: world.txt
        dest: foo/world.txt.bak