---
- name: Hello World
  hosts: myservers
  connection: local
  tasks:

    - name: Disk usage from command module
      command: df -h
      register: space
    - debug:
        var: space

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    - name: Create file
      ansible.builtin.file:
        path: gantengv1.txt
        state: touch

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    - name: Copy file
      ansible.builtin.copy:
        src: world.txt
        dest: ganteng.txt